# fly.toml app configuration file generated for divine-hill-8950 on 2023-08-22T17:56:44+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "divine-hill-8950"
primary_region = "arn"

[build]
  PORT = "3001" # add this


[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
